import React from 'react'
import Head from 'next/head'
import { Col, Container, Row } from 'react-bootstrap'
import NavbarComponent from '../src/components/navbar'
import ProfileAvatarComponent from '../src/components/profile-avatar'
import ProfileDescriptionComponent from '../src/components/profile-description'
import ProfileDetailComponent from '../src/components/profile-detail'
import ProfileSocialComponent from '../src/components/profile-social'
import TechnicalQuestionComponent from '../src/components/technical-question'

function IndexPage() {
  return (
    <React.Fragment>
      <Head>
        <title>System Developer Technical | Kelvin Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <NavbarComponent />
        <Container className="py-5">
          <Row className="mb-4">
            <Col lg="4">
              <ProfileAvatarComponent />
              <ProfileSocialComponent />
            </Col>
            <Col lg="8">
              <ProfileDetailComponent />
              <ProfileDescriptionComponent />
            </Col>
          </Row>
          <Row>
            <Col>
              <TechnicalQuestionComponent />
            </Col>
          </Row>
        </Container>
      </section>
    </React.Fragment>
  )
}

export default IndexPage
